export const coursesData = [
  // Apparel & Handloom (5)
  {
    key: 'crs_self_employed_tailor',
    title: 'Self Employed Tailor Certificate Program',
    provider: 'Apparel Made-Ups & Home Furnishing Sector Skill Council (AMHSSC)',
    nsqfLevel: 3,
    qpCode: 'AMH/Q1947',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['sewing_machine_operation', 'garment_pattern_cutting', 'apparel_quality_checking'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AMH/Q1947'
  },
  {
    key: 'crs_sewing_machine_operator',
    title: 'Sewing Machine Operator (Export Unit)',
    provider: 'AMHSSC / PMKVY Training Provider',
    nsqfLevel: 2,
    qpCode: 'AMH/Q0301',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['sewing_machine_operation', 'industrial_sewing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AMH/Q0301'
  },
  {
    key: 'crs_hand_embroiderer',
    title: 'Hand Embroiderer (Zari & Aari Craft)',
    provider: 'AMHSSC / National Skill Development Corporation',
    nsqfLevel: 2,
    qpCode: 'AMH/Q1001',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['hand_embroidery', 'fashion_accessory_making'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AMH/Q1001'
  },
  {
    key: 'crs_handloom_weaver',
    title: 'Traditional Handloom Weaver Skilling',
    provider: 'Handloom & Textile Sector Skill Council',
    nsqfLevel: 3,
    qpCode: 'TSC/Q7301',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['handloom_weaving', 'textile_screen_printing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/TSC/Q7301'
  },
  {
    key: 'crs_textile_block_printer',
    title: 'Textile Screen and Block Printer',
    provider: 'Textile Sector Skill Council',
    nsqfLevel: 2,
    qpCode: 'TSC/Q7303',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['textile_screen_printing', 'apparel_quality_checking'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/TSC/Q7303'
  },

  // Food Processing (5)
  {
    key: 'crs_pickle_chutney_maker',
    title: 'Commercial Pickle and Jam Processing',
    provider: 'Food Industry Capacity & Skill Initiative (FICSI)',
    nsqfLevel: 3,
    qpCode: 'FIC/Q0102',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['pickle_jam_preservation', 'food_packaging_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/FIC/Q0102'
  },
  {
    key: 'crs_baking_technician',
    title: 'Artisanal & Commercial Baking Program',
    provider: 'FICSI / PMKVY 4.0 Center',
    nsqfLevel: 3,
    qpCode: 'FIC/Q5005',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['commercial_baking', 'food_packaging_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/FIC/Q5005'
  },
  {
    key: 'crs_spice_processing',
    title: 'Spice Grinding and Processing Operator',
    provider: 'FICSI',
    nsqfLevel: 3,
    qpCode: 'FIC/Q8501',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['spice_grinding_blending', 'food_packaging_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/FIC/Q8501'
  },
  {
    key: 'crs_dairy_processing_assistant',
    title: 'Dairy Products Processing Technician',
    provider: 'FICSI / Telangana Dairy Development Coop',
    nsqfLevel: 3,
    qpCode: 'FIC/Q2001',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['dairy_product_making', 'food_packaging_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/FIC/Q2001'
  },
  {
    key: 'crs_grain_mill_operator',
    title: 'Flour & Pulse Mill Machine Operator',
    provider: 'FICSI',
    nsqfLevel: 3,
    qpCode: 'FIC/Q1003',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['grain_milling_processing', 'food_packaging_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/FIC/Q1003'
  },

  // Agriculture (5)
  {
    key: 'crs_organic_grower',
    title: 'Certified Organic Grower and Compost Producer',
    provider: 'Agriculture Skill Council of India (ASCI)',
    nsqfLevel: 4,
    qpCode: 'AGR/Q1201',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['organic_compost_vermicompost', 'integrated_pest_management'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q1201'
  },
  {
    key: 'crs_micro_irrigation_tech',
    title: 'Micro Irrigation Systems Technician',
    provider: 'ASCI / PM-KSY Training Partner',
    nsqfLevel: 3,
    qpCode: 'AGR/Q1002',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['drip_irrigation_maintenance', 'sanitary_plumbing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q1002'
  },
  {
    key: 'crs_polyhouse_grower',
    title: 'Greenhouse & Polyhouse Cultivation',
    provider: 'ASCI / Horticulture Dept Telangana',
    nsqfLevel: 3,
    qpCode: 'AGR/Q0801',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['polyhouse_nursery_management', 'drip_irrigation_maintenance'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q0801'
  },
  {
    key: 'crs_tractor_operator',
    title: 'Tractor Mechanic and Operator',
    provider: 'ASCI',
    nsqfLevel: 3,
    qpCode: 'AGR/Q1101',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['tractor_farm_machinery'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q1101'
  },
  {
    key: 'crs_medicinal_crops_cultivator',
    title: 'Medicinal Plants Cultivator',
    provider: 'ASCI',
    nsqfLevel: 3,
    qpCode: 'AGR/Q0901',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['medicinal_plant_cultivation'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q0901'
  },

  // Dairy & Animal Husbandry (5)
  {
    key: 'crs_small_dairy_farmer',
    title: 'Commercial Small Dairy Farmer',
    provider: 'ASCI / Animal Husbandry Department',
    nsqfLevel: 3,
    qpCode: 'AGR/Q4101',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['milking_machine_handling', 'cattle_feed_nutrition', 'dairy_shed_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q4101'
  },
  {
    key: 'crs_artificial_insemination_technician',
    title: 'Artificial Insemination & Livestock Breeding',
    provider: 'ASCI / Veterinary University',
    nsqfLevel: 4,
    qpCode: 'AGR/Q4801',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 4,
    skillsGained: ['artificial_insemination_support', 'dairy_shed_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q4801'
  },
  {
    key: 'crs_goat_farmer',
    title: 'Stall-Fed Goat & Sheep Rearing',
    provider: 'ASCI',
    nsqfLevel: 3,
    qpCode: 'AGR/Q4301',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['goat_sheep_rearing', 'cattle_feed_nutrition'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q4301'
  },
  {
    key: 'crs_poultry_farmer',
    title: 'Broiler & Layer Farm Supervisor',
    provider: 'ASCI',
    nsqfLevel: 3,
    qpCode: 'AGR/Q4201',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['poultry_farm_brooding'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q4201'
  },
  {
    key: 'crs_bulk_milk_cooler_operator',
    title: 'Bulk Milk Chilling Center Operator',
    provider: 'FICSI',
    nsqfLevel: 3,
    qpCode: 'FIC/Q2003',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['milking_machine_handling', 'dairy_shed_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/FIC/Q2003'
  },

  // Electronics & Hardware (5)
  {
    key: 'crs_suryamitra_solar_installer',
    title: 'Suryamitra Solar PV System Installer',
    provider: 'Skill Council for Green Jobs (SCGJ)',
    nsqfLevel: 4,
    qpCode: 'SGJ/Q0101',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['solar_panel_installation', 'house_wiring_electrical'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/SGJ/Q0101'
  },
  {
    key: 'crs_field_technician_home_appliances',
    title: 'Field Technician Home Appliances',
    provider: 'Electronics Sector Skills Council of India (ESSCI)',
    nsqfLevel: 3,
    qpCode: 'ELE/Q3104',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['home_appliance_repair', 'house_wiring_electrical'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/ELE/Q3104'
  },
  {
    key: 'crs_mobile_repair_technician',
    title: 'Smartphone Repair & Hardware Servicing',
    provider: 'ESSCI',
    nsqfLevel: 3,
    qpCode: 'ELE/Q8104',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['smartphone_hardware_repair'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/ELE/Q8104'
  },
  {
    key: 'crs_rac_field_technician',
    title: 'Refrigeration and Air Conditioning Servicing',
    provider: 'ESSCI',
    nsqfLevel: 4,
    qpCode: 'ELE/Q3102',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 4,
    skillsGained: ['refrigeration_ac_servicing', 'house_wiring_electrical'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/ELE/Q3102'
  },
  {
    key: 'crs_cctv_installation_technician',
    title: 'CCTV & Security System Technician',
    provider: 'ESSCI',
    nsqfLevel: 3,
    qpCode: 'ELE/Q4605',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['cctv_security_installation', 'house_wiring_electrical'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/ELE/Q4605'
  },

  // Construction & Plumbing (5)
  {
    key: 'crs_general_mason',
    title: 'General Masonry and Bricklaying',
    provider: 'Construction Skill Development Council of India (CSDCI)',
    nsqfLevel: 3,
    qpCode: 'CON/Q0103',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['masonry_bricklaying', 'tile_marble_laying'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/CON/Q0103'
  },
  {
    key: 'crs_general_plumber',
    title: 'General Plumber Plumbing & Sanitation',
    provider: 'Plumbing Care Skill Council (IPSC)',
    nsqfLevel: 3,
    qpCode: 'PSC/Q0104',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['sanitary_plumbing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/PSC/Q0104'
  },
  {
    key: 'crs_welder_structural',
    title: 'Manual Metal Arc Welder',
    provider: 'Capital Goods Skill Council (CGSC)',
    nsqfLevel: 3,
    qpCode: 'CSC/Q0204',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['structural_arc_welding'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/CSC/Q0204'
  },
  {
    key: 'crs_construction_painter',
    title: 'Construction Painter & Decorator',
    provider: 'Paints and Coatings Skill Council (PCSC)',
    nsqfLevel: 2,
    qpCode: 'PCS/Q5001',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['building_painting_distempering'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/PCS/Q5001'
  },
  {
    key: 'crs_shuttering_carpenter',
    title: 'Formwork & Shuttering Carpenter',
    provider: 'CSDCI',
    nsqfLevel: 3,
    qpCode: 'CON/Q0303',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['carpentry_shuttering'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/CON/Q0303'
  },

  // Retail & Micro-Commerce (5)
  {
    key: 'crs_retail_sales_associate',
    title: 'Retail Sales Associate Certification',
    provider: 'Retailers Association Skill Council of India (RASCI)',
    nsqfLevel: 3,
    qpCode: 'RAS/Q0104',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['retail_sales_customer_service', 'pos_digital_billing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/RAS/Q0104'
  },
  {
    key: 'crs_micro_retail_entrepreneur',
    title: 'Micro-Retail Store Management & POS',
    provider: 'RASCI / Ministry of Rural Development',
    nsqfLevel: 3,
    qpCode: 'RAS/Q0601',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['micro_business_bookkeeping', 'pos_digital_billing', 'inventory_stock_replenishment'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/RAS/Q0601'
  },
  {
    key: 'crs_ecommerce_logistics_associate',
    title: 'E-commerce Warehouse & Delivery Associate',
    provider: 'Logistics Sector Skill Council (LSSC)',
    nsqfLevel: 2,
    qpCode: 'LSC/Q2301',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['ecommerce_order_fulfillment', 'inventory_stock_replenishment'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/LSC/Q2301'
  },
  {
    key: 'crs_rural_distributor',
    title: 'Rural Sales & Distribution Executive',
    provider: 'RASCI',
    nsqfLevel: 3,
    qpCode: 'RAS/Q0302',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['rural_market_vending', 'retail_sales_customer_service'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/RAS/Q0302'
  },
  {
    key: 'crs_cashier_pos_operator',
    title: 'Retail Cashier and Digital Payments',
    provider: 'RASCI',
    nsqfLevel: 2,
    qpCode: 'RAS/Q0101',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 1,
    skillsGained: ['pos_digital_billing', 'micro_business_bookkeeping'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/RAS/Q0101'
  },

  // Digital & IT-ITeS (4)
  {
    key: 'crs_domestic_data_entry_operator',
    title: 'Domestic Data Entry Operator (DDEO)',
    provider: 'IT-ITeS Sector Skills Council NASSCOM',
    nsqfLevel: 3,
    qpCode: 'SSC/Q2212',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 2,
    skillsGained: ['data_entry_vernacular_typing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/SSC/Q2212'
  },
  {
    key: 'crs_csc_vle_entrepreneurship',
    title: 'Village Level Digital Services (VLE) Skilling',
    provider: 'CSC Academy / NASSCOM',
    nsqfLevel: 4,
    qpCode: 'SSC/Q0508',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['csc_citizen_service_delivery', 'digital_banking_dbt_assistance', 'basic_computer_troubleshooting'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/SSC/Q0508'
  },
  {
    key: 'crs_crm_domestic_voice',
    title: 'CRM Domestic Voice & Regional Inbound Support',
    provider: 'NASSCOM / PMKVY Center',
    nsqfLevel: 4,
    qpCode: 'SSC/Q2210',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['bpo_voice_inbound_support', 'data_entry_vernacular_typing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/SSC/Q2210'
  },
  {
    key: 'crs_hardware_network_assistant',
    title: 'Hardware & Desktop Support Assistant',
    provider: 'NASSCOM',
    nsqfLevel: 3,
    qpCode: 'SSC/Q0110',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['basic_computer_troubleshooting'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/SSC/Q0110'
  },

  // Healthcare Support (4)
  {
    key: 'crs_general_duty_assistant',
    title: 'General Duty Assistant (GDA)',
    provider: 'Healthcare Sector Skill Council (HSSC)',
    nsqfLevel: 3,
    qpCode: 'HSS/Q5101',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 4,
    skillsGained: ['general_duty_hospital_assistance', 'first_aid_emergency_response'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/HSS/Q5101'
  },
  {
    key: 'crs_home_health_aide',
    title: 'Home Health Aide & Geriatric Care',
    provider: 'HSSC',
    nsqfLevel: 3,
    qpCode: 'HSS/Q5102',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['elderly_patient_home_care', 'first_aid_emergency_response'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/HSS/Q5102'
  },
  {
    key: 'crs_community_health_worker',
    title: 'Community Health Mobilizer & Nutrition Counselor',
    provider: 'HSSC / National Health Mission',
    nsqfLevel: 3,
    qpCode: 'HSS/Q8601',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['maternal_child_nutrition_guidance', 'community_sanitation_survey'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/HSS/Q8601'
  },
  {
    key: 'crs_pharmacy_assistant',
    title: 'Retail Pharmacy Assistant',
    provider: 'HSSC',
    nsqfLevel: 3,
    qpCode: 'HSS/Q5401',
    mode: 'offline',
    costInr: 0,
    language: 'te',
    durationMonths: 3,
    skillsGained: ['pharmacy_retail_assistant'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/HSS/Q5401'
  }
];
