export const occupationsData = [
  // 1. Tailoring & Apparel (3)
  {
    key: 'self_employed_tailor',
    title: 'Self Employed Tailor',
    titles: { en: 'Self Employed Tailor', hi: 'स्वरोजगार दर्जी', te: 'స్వయం ఉపాధి టైలర్' },
    sector: 'Apparel & Handloom',
    nsqfLevel: 3,
    ncoCode: '7531.0100',
    incomeMin: 12000,
    incomeMax: 30000,
    workModes: ['home', 'workshop', 'store'],
    travelRequired: false,
    minEducation: 'Primary School',
    selfEmploymentViable: true,
    requiredSkills: ['sewing_machine_operation', 'garment_pattern_cutting', 'apparel_quality_checking'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AMH/Q1947'
  },
  {
    key: 'hand_embroiderer',
    title: 'Hand Embroiderer',
    titles: { en: 'Hand Embroiderer', hi: 'हाथ का कढ़ाईकार', te: 'చేతి ఎంబ్రాయిడరీ నిపుణుడు' },
    sector: 'Apparel & Handloom',
    nsqfLevel: 2,
    ncoCode: '7533.0200',
    incomeMin: 9000,
    incomeMax: 22000,
    workModes: ['home', 'workshop'],
    travelRequired: false,
    minEducation: 'Primary School',
    selfEmploymentViable: true,
    requiredSkills: ['hand_embroidery', 'fashion_accessory_making'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AMH/Q1001'
  },
  {
    key: 'apparel_sewing_operator',
    title: 'Sewing Machine Operator',
    titles: { en: 'Sewing Machine Operator', hi: 'सिलाई मशीन संचालक', te: 'కుట్టు మిషన్ ఆపరేటర్' },
    sector: 'Apparel & Handloom',
    nsqfLevel: 2,
    ncoCode: '8153.0101',
    incomeMin: 11000,
    incomeMax: 20000,
    workModes: ['factory', 'workshop'],
    travelRequired: false,
    minEducation: 'Primary School',
    selfEmploymentViable: false,
    requiredSkills: ['sewing_machine_operation', 'industrial_sewing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AMH/Q0301'
  },

  // 2. Food Processing (3)
  {
    key: 'pickle_making_technician',
    title: 'Pickle and Chutney Maker',
    titles: { en: 'Pickle and Chutney Maker', hi: 'अचार और चटनी निर्माता', te: 'ఊరగాయల తయారీదారు' },
    sector: 'Food Processing',
    nsqfLevel: 3,
    ncoCode: '7514.0200',
    incomeMin: 12000,
    incomeMax: 28000,
    workModes: ['home', 'workshop'],
    travelRequired: false,
    minEducation: 'Primary School',
    selfEmploymentViable: true,
    requiredSkills: ['pickle_jam_preservation', 'food_packaging_hygiene', 'spice_grinding_blending'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/FIC/Q0102'
  },
  {
    key: 'baking_technician',
    title: 'Baking Technician',
    titles: { en: 'Baking Technician', hi: 'बेकिंग तकनीशियन', te: 'బేకరీ టెక్నీషియన్' },
    sector: 'Food Processing',
    nsqfLevel: 3,
    ncoCode: '7512.0101',
    incomeMin: 14000,
    incomeMax: 32000,
    workModes: ['workshop', 'store'],
    travelRequired: false,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['commercial_baking', 'food_packaging_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/FIC/Q5005'
  },
  {
    key: 'spice_processing_technician',
    title: 'Spice Processing Technician',
    titles: { en: 'Spice Processing Technician', hi: 'मसाला प्रसंस्करण तकनीशियन', te: 'మసాలా ప్రాసెసింగ్ టెక్నీషియన్' },
    sector: 'Food Processing',
    nsqfLevel: 3,
    ncoCode: '7514.0300',
    incomeMin: 13000,
    incomeMax: 26000,
    workModes: ['workshop', 'factory'],
    travelRequired: false,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['spice_grinding_blending', 'grain_milling_processing', 'food_packaging_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/FIC/Q8501'
  },

  // 3. Agriculture (3)
  {
    key: 'organic_grower',
    title: 'Organic Grower',
    titles: { en: 'Organic Grower', hi: 'जैविक किसान', te: 'సేంద్రీయ రైతు' },
    sector: 'Agriculture',
    nsqfLevel: 4,
    ncoCode: '6111.0201',
    incomeMin: 15000,
    incomeMax: 35000,
    workModes: ['field'],
    travelRequired: false,
    minEducation: 'Primary School',
    selfEmploymentViable: true,
    requiredSkills: ['organic_compost_vermicompost', 'integrated_pest_management'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q1201'
  },
  {
    key: 'micro_irrigation_technician',
    title: 'Micro Irrigation Technician',
    titles: { en: 'Micro Irrigation Technician', hi: 'सूक्ष्म सिंचाई तकनीशियन', te: 'మైక్రో ఇరిగేషన్ టెక్నీషియన్' },
    sector: 'Agriculture',
    nsqfLevel: 3,
    ncoCode: '7233.0501',
    incomeMin: 14000,
    incomeMax: 28000,
    workModes: ['field', 'workshop'],
    travelRequired: true,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['drip_irrigation_maintenance', 'sanitary_plumbing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q1002'
  },
  {
    key: 'polyhouse_grower',
    title: 'Polyhouse Vegetable Grower',
    titles: { en: 'Polyhouse Vegetable Grower', hi: 'पॉलीहाउस सब्जी उत्पादक', te: 'పాలీహౌస్ కూరగాయల సాగుదారు' },
    sector: 'Agriculture',
    nsqfLevel: 3,
    ncoCode: '6113.0101',
    incomeMin: 16000,
    incomeMax: 40000,
    workModes: ['field'],
    travelRequired: false,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['polyhouse_nursery_management', 'drip_irrigation_maintenance', 'integrated_pest_management'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q0801'
  },
  {
    key: 'tractor_operator',
    title: 'Tractor and Farm Machinery Operator',
    titles: { en: 'Tractor and Farm Machinery Operator', hi: 'ट्रैक्टर एवं कृषि मशीन ऑपरेटर', te: 'ట్రాక్టర్ మరియు వ్యవసాయ యంత్రాల ఆపరేటర్' },
    sector: 'Agriculture',
    nsqfLevel: 3,
    ncoCode: '8341.0101',
    incomeMin: 16000,
    incomeMax: 36000,
    workModes: ['field', 'workshop'],
    travelRequired: true,
    minEducation: 'Primary School',
    selfEmploymentViable: true,
    requiredSkills: ['tractor_farm_machinery'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q1101'
  },
  {
    key: 'medicinal_crops_cultivator',
    title: 'Medicinal Plants Cultivator',
    titles: { en: 'Medicinal Plants Cultivator', hi: 'औषधीय पौध कृषक', te: 'ఔషధ మొక్కల సాగుదారు' },
    sector: 'Agriculture',
    nsqfLevel: 3,
    ncoCode: '6113.0201',
    incomeMin: 14000,
    incomeMax: 32000,
    workModes: ['field'],
    travelRequired: false,
    minEducation: 'Primary School',
    selfEmploymentViable: true,
    requiredSkills: ['medicinal_plant_cultivation'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q0901'
  },

  // 4. Dairy & Animal Husbandry (3)
  {
    key: 'dairy_farmer_entrepreneur',
    title: 'Small Dairy Farmer',
    titles: { en: 'Small Dairy Farmer', hi: 'लघु डेयरी किसान', te: 'చిన్న పాడి రైతు' },
    sector: 'Dairy & Animal Husbandry',
    nsqfLevel: 3,
    ncoCode: '6121.0100',
    incomeMin: 18000,
    incomeMax: 45000,
    workModes: ['home', 'field'],
    travelRequired: false,
    minEducation: 'Primary School',
    selfEmploymentViable: true,
    requiredSkills: ['milking_machine_handling', 'cattle_feed_nutrition', 'dairy_shed_hygiene', 'dairy_product_making'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q4101'
  },
  {
    key: 'ai_veterinary_assistant',
    title: 'Artificial Insemination Technician',
    titles: { en: 'Artificial Insemination Technician', hi: 'कृत्रिम गर्भाधान तकनीशियन', te: 'కృత్రిమ గర్భధారణ టెక్నీషియన్' },
    sector: 'Dairy & Animal Husbandry',
    nsqfLevel: 4,
    ncoCode: '3240.0101',
    incomeMin: 15000,
    incomeMax: 30000,
    workModes: ['field'],
    travelRequired: true,
    minEducation: 'High School',
    selfEmploymentViable: true,
    requiredSkills: ['artificial_insemination_support', 'dairy_shed_hygiene'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q4801'
  },
  {
    key: 'goat_sheep_farmer',
    title: 'Commercial Goat Farmer',
    titles: { en: 'Commercial Goat Farmer', hi: 'वाणिज्यिक बकरी पालक', te: 'వాణిజ్య మేకల పెంపకందారు' },
    sector: 'Dairy & Animal Husbandry',
    nsqfLevel: 3,
    ncoCode: '6121.0300',
    incomeMin: 14000,
    incomeMax: 35000,
    workModes: ['field', 'home'],
    travelRequired: false,
    minEducation: 'Primary School',
    selfEmploymentViable: true,
    requiredSkills: ['goat_sheep_rearing', 'cattle_feed_nutrition'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/AGR/Q4301'
  },

  // 5. Electronics & Hardware (3)
  {
    key: 'solar_pv_installer',
    title: 'Solar PV System Installer (Suryamitra)',
    titles: { en: 'Solar PV System Installer (Suryamitra)', hi: 'सोलर पीवी इंस्टॉलर (सूर्यमित्र)', te: 'సోలార్ పివి ఇన్స్టాలర్ (సూర్యమిత్ర)' },
    sector: 'Electronics & Hardware',
    nsqfLevel: 4,
    ncoCode: '7411.0102',
    incomeMin: 16000,
    incomeMax: 35000,
    workModes: ['field', 'workshop'],
    travelRequired: true,
    minEducation: 'High School',
    selfEmploymentViable: true,
    requiredSkills: ['solar_panel_installation', 'house_wiring_electrical'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/SGJ/Q0101'
  },
  {
    key: 'field_technician_home_appliances',
    title: 'Field Technician Other Home Appliances',
    titles: { en: 'Field Technician Other Home Appliances', hi: 'घरेलू उपकरण फील्ड तकनीशियन', te: 'గృహోపకరణాల ఫీల్డ్ టెక్నీషియన్' },
    sector: 'Electronics & Hardware',
    nsqfLevel: 3,
    ncoCode: '7412.0201',
    incomeMin: 15000,
    incomeMax: 30000,
    workModes: ['field', 'workshop'],
    travelRequired: true,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['home_appliance_repair', 'house_wiring_electrical'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/ELE/Q3104'
  },
  {
    key: 'mobile_phone_repair_technician',
    title: 'Mobile Phone Hardware Technician',
    titles: { en: 'Mobile Phone Hardware Technician', hi: 'मोबाइल फोन हार्डवेयर तकनीशियन', te: 'మొబైల్ ఫోన్ రిపేర్ టెక్నీషియన్' },
    sector: 'Electronics & Hardware',
    nsqfLevel: 3,
    ncoCode: '7422.0203',
    incomeMin: 15000,
    incomeMax: 35000,
    workModes: ['store', 'workshop'],
    travelRequired: false,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['smartphone_hardware_repair'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/ELE/Q8104'
  },

  // 6. Construction & Fabrication (3)
  {
    key: 'general_mason',
    title: 'General Mason',
    titles: { en: 'General Mason', hi: 'सामान्य राजमिस्त्री', te: 'భవన నిర్మాణ మేస్త్రీ' },
    sector: 'Construction',
    nsqfLevel: 3,
    ncoCode: '7112.0100',
    incomeMin: 18000,
    incomeMax: 38000,
    workModes: ['field'],
    travelRequired: true,
    minEducation: 'Primary School',
    selfEmploymentViable: true,
    requiredSkills: ['masonry_bricklaying', 'tile_marble_laying'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/CON/Q0103'
  },
  {
    key: 'plumber_general',
    title: 'General Plumber',
    titles: { en: 'General Plumber', hi: 'सामान्य प्लंबर', te: 'జనరల్ ప్లంబర్' },
    sector: 'Construction',
    nsqfLevel: 3,
    ncoCode: '7126.0101',
    incomeMin: 16000,
    incomeMax: 32000,
    workModes: ['field', 'workshop'],
    travelRequired: true,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['sanitary_plumbing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/PSC/Q0104'
  },
  {
    key: 'welder_structural',
    title: 'Structural Welder and Fabricator',
    titles: { en: 'Structural Welder and Fabricator', hi: 'संरचनात्मक वेल्डर एवं फैब्रिकेटर', te: 'స్ట్రక్చరల్ వెల్డర్ మరియు ఫ్యాబ్రికేటర్' },
    sector: 'Construction',
    nsqfLevel: 3,
    ncoCode: '7212.0100',
    incomeMin: 16000,
    incomeMax: 34000,
    workModes: ['workshop', 'field'],
    travelRequired: false,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['structural_arc_welding'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/CSC/Q0204'
  },

  // 7. Retail & Micro-Commerce (3)
  {
    key: 'retail_sales_associate',
    title: 'Retail Sales Associate',
    titles: { en: 'Retail Sales Associate', hi: 'खुदरा बिक्री सहयोगी', te: 'రిటైల్ సేల్స్ అసోసియేట్' },
    sector: 'Retail & Commerce',
    nsqfLevel: 3,
    ncoCode: '5223.0101',
    incomeMin: 13000,
    incomeMax: 24000,
    workModes: ['store'],
    travelRequired: false,
    minEducation: 'High School',
    selfEmploymentViable: false,
    requiredSkills: ['retail_sales_customer_service', 'pos_digital_billing', 'inventory_stock_replenishment'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/RAS/Q0104'
  },
  {
    key: 'micro_retailer_kirana_owner',
    title: 'Micro Retailer and Kirana Store Owner',
    titles: { en: 'Micro Retailer and Kirana Store Owner', hi: 'सूक्ष्म व्यापारी एवं किराना स्टोर संचालक', te: 'కిరాణా మరియు చిన్న వ్యాపారి' },
    sector: 'Retail & Commerce',
    nsqfLevel: 3,
    ncoCode: '5221.0100',
    incomeMin: 15000,
    incomeMax: 40000,
    workModes: ['store', 'home'],
    travelRequired: false,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['micro_business_bookkeeping', 'pos_digital_billing', 'inventory_stock_replenishment', 'rural_market_vending'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/RAS/Q0601'
  },
  {
    key: 'rural_market_distributor',
    title: 'Rural Aggregator and Distributor',
    titles: { en: 'Rural Aggregator and Distributor', hi: 'ग्रामीण वितरक एवं संग्रहकर्ता', te: 'గ్రామీణ పంపిణీదారుడు' },
    sector: 'Retail & Commerce',
    nsqfLevel: 3,
    ncoCode: '5222.0200',
    incomeMin: 14000,
    incomeMax: 30000,
    workModes: ['field', 'store'],
    travelRequired: true,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['rural_market_vending', 'ecommerce_order_fulfillment'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/RAS/Q0302'
  },

  // 8. Digital & IT-ITeS (3)
  {
    key: 'domestic_data_entry_operator',
    title: 'Domestic Data Entry Operator',
    titles: { en: 'Domestic Data Entry Operator', hi: 'घरेलू डेटा एंट्री ऑपरेटर', te: 'డేటా ఎంట్రీ ఆపరేటర్' },
    sector: 'Digital & IT-ITeS',
    nsqfLevel: 3,
    ncoCode: '4132.0402',
    incomeMin: 12000,
    incomeMax: 22000,
    workModes: ['office', 'home'],
    travelRequired: false,
    minEducation: 'High School',
    selfEmploymentViable: false,
    requiredSkills: ['data_entry_vernacular_typing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/SSC/Q2212'
  },
  {
    key: 'csc_village_level_entrepreneur',
    title: 'Village Level Digital Service Entrepreneur (VLE)',
    titles: { en: 'Village Level Digital Service Entrepreneur (VLE)', hi: 'ग्राम स्तरीय डिजिटल उद्यमी (VLE)', te: 'గ్రామ స్థాయి డిజిటల్ సేవా వ్యవస్థాపకుడు (VLE)' },
    sector: 'Digital & IT-ITeS',
    nsqfLevel: 4,
    ncoCode: '3514.0100',
    incomeMin: 16000,
    incomeMax: 45000,
    workModes: ['store', 'office'],
    travelRequired: false,
    minEducation: 'High School',
    selfEmploymentViable: true,
    requiredSkills: ['csc_citizen_service_delivery', 'digital_banking_dbt_assistance', 'basic_computer_troubleshooting'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/SSC/Q0508'
  },
  {
    key: 'crm_voice_associate',
    title: 'CRM Domestic Voice Associate',
    titles: { en: 'CRM Domestic Voice Associate', hi: 'सीआरएम घरेलू वॉयस सहयोगी', te: 'సిఆర్‌ఎం వాయిస్ అసోసియేట్' },
    sector: 'Digital & IT-ITeS',
    nsqfLevel: 4,
    ncoCode: '5244.0101',
    incomeMin: 15000,
    incomeMax: 26000,
    workModes: ['office'],
    travelRequired: false,
    minEducation: 'High School',
    selfEmploymentViable: false,
    requiredSkills: ['bpo_voice_inbound_support', 'data_entry_vernacular_typing'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/SSC/Q2210'
  },

  // 9. Healthcare & Community Support (3)
  {
    key: 'general_duty_assistant',
    title: 'General Duty Assistant (Healthcare)',
    titles: { en: 'General Duty Assistant (Healthcare)', hi: 'सामान्य ड्यूटी सहायक (स्वास्थ्य)', te: 'జనరల్ డ్యూటీ అసిస్టెంట్ (ఆరోగ్యం)' },
    sector: 'Healthcare Support',
    nsqfLevel: 3,
    ncoCode: '5321.0100',
    incomeMin: 14000,
    incomeMax: 25000,
    workModes: ['office'],
    travelRequired: false,
    minEducation: 'High School',
    selfEmploymentViable: false,
    requiredSkills: ['general_duty_hospital_assistance', 'first_aid_emergency_response'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/HSS/Q5101'
  },
  {
    key: 'home_health_aide',
    title: 'Home Health Aide',
    titles: { en: 'Home Health Aide', hi: 'गृह स्वास्थ्य सहायक', te: 'హోమ్ హెల్త్ ఎయిడ్' },
    sector: 'Healthcare Support',
    nsqfLevel: 3,
    ncoCode: '5322.0100',
    incomeMin: 15000,
    incomeMax: 30000,
    workModes: ['home', 'field'],
    travelRequired: true,
    minEducation: 'Middle School',
    selfEmploymentViable: true,
    requiredSkills: ['elderly_patient_home_care', 'first_aid_emergency_response'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/HSS/Q5102'
  },
  {
    key: 'community_health_worker_poshan',
    title: 'Community Nutrition and Health Mobilizer',
    titles: { en: 'Community Nutrition and Health Mobilizer', hi: 'सामुदायिक पोषण एवं स्वास्थ्य कार्यकर्ता', te: 'కమ్యూనిటీ పోషణ మరియు ఆరోగ్య కార్యకర్త' },
    sector: 'Healthcare Support',
    nsqfLevel: 3,
    ncoCode: '3253.0100',
    incomeMin: 12000,
    incomeMax: 20000,
    workModes: ['field'],
    travelRequired: true,
    minEducation: 'Middle School',
    selfEmploymentViable: false,
    requiredSkills: ['maternal_child_nutrition_guidance', 'community_sanitation_survey'],
    source: 'https://www.skillindiadigital.gov.in/courses/detail/HSS/Q8601'
  }
];
