/* admin/PerspectivePlan.jsx: Generate and print district livelihood action plan
   SIH26097 PM-AJAY Livelihood Assistant */
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../../AuthContext.jsx';
import { SkeletonCard, EmptyState } from '../../components.jsx';
import { postGeneratePlan, getPlans } from '../../api.js';
import { useToast } from '../../ToastContext.jsx';
import './PerspectivePlan.css';

const DISTRICTS = ['Warangal', 'Adilabad', 'Nalgonda'];

function PlanDocument({ plan }) {
  const date = plan.createdAt ? new Date(plan.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }) : new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
  return (
    <div className="plan-doc" id="plan-print-area">
      {/* Header */}
      <div className="plan-header">
        <div className="plan-logo">🌱</div>
        <div>
          <h1 className="plan-title">District Livelihood Action Plan</h1>
          <p className="plan-subtitle">PM-AJAY | GIA Component | SIH26097</p>
          <p className="plan-meta">{plan.district} · Generated {date}</p>
        </div>
      </div>

      {/* Key numbers */}
      <div className="plan-kpis">
        <div className="plan-kpi">
          <div className="plan-kpi-val">{plan.targetBeneficiaries?.toLocaleString()}</div>
          <div className="plan-kpi-lbl">Target Beneficiaries</div>
        </div>
        <div className="plan-kpi">
          <div className="plan-kpi-val">₹{(plan.budgetInr / 100000).toFixed(1)}L</div>
          <div className="plan-kpi-lbl">Total Budget</div>
        </div>
        <div className="plan-kpi">
          <div className="plan-kpi-val">{plan.projectedImpact?.overallPlacementRatePct}%</div>
          <div className="plan-kpi-lbl">Placement Target</div>
        </div>
        <div className="plan-kpi">
          <div className="plan-kpi-val">₹{plan.projectedImpact?.avgMonthlyIncomeInr?.toLocaleString()}</div>
          <div className="plan-kpi-lbl">Avg Monthly Income</div>
        </div>
      </div>

      {/* Employment split */}
      <div className="plan-section">
        <h2>Employment Pathway Split</h2>
        <div className="plan-split">
          <div className="plan-split-item" style={{ background: 'hsl(30 100% 50% / 0.1)' }}>
            <span style={{ fontSize: '2rem' }}>🏪</span>
            <strong>{plan.projectedImpact?.selfEmploymentCount}</strong>
            <span>Self Employment</span>
          </div>
          <div className="plan-split-item" style={{ background: 'hsl(204 85% 52% / 0.1)' }}>
            <span style={{ fontSize: '2rem' }}>💼</span>
            <strong>{plan.projectedImpact?.wageEmploymentCount}</strong>
            <span>Wage Employment</span>
          </div>
        </div>
      </div>

      {/* Allocations table */}
      <div className="plan-section">
        <h2>Sectoral Allocation Plan</h2>
        <table className="plan-table">
          <thead>
            <tr>
              <th>Sector / Occupation</th>
              <th>Beneficiaries</th>
              <th>Budget Allocated</th>
              <th>Expected Placements</th>
              <th>Training Partners</th>
            </tr>
          </thead>
          <tbody>
            {(plan.allocations || []).map((a, i) => (
              <tr key={i}>
                <td>
                  <strong>{a.sector}</strong>
                  <br /><span style={{ fontSize: '0.75rem', opacity: 0.7 }}>{a.occupationKey}</span>
                </td>
                <td>{a.beneficiaryCount?.toLocaleString()}</td>
                <td>₹{(a.allocatedBudgetInr / 100000).toFixed(2)}L</td>
                <td>{a.expectedPlacements?.toLocaleString()}</td>
                <td style={{ fontSize: '0.75rem' }}>{(a.trainingPartners || []).join(', ')}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="plan-footer">
        <p>This plan is indicative. Actual targets are subject to district capacity assessment and state approval.</p>
        <p>Generated by SIH26097 AI Livelihood Mapping System | PM-AJAY GIA</p>
      </div>
    </div>
  );
}

export default function PerspectivePlan() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const toast = useToast();

  const [plans, setPlans] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selected, setSelected] = useState(null);
  const [form, setForm] = useState({
    district: user?.district || 'Warangal',
    targetBeneficiaries: 500,
    budgetInr: 5000000,
  });

  useEffect(() => {
    getPlans()
      .then((res) => {
        const p = res.data.plans || [];
        setPlans(p);
        if (p.length > 0) setSelected(p[0]);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    setGenerating(true);
    try {
      const res = await postGeneratePlan(form);
      const newPlan = res.data.plan;
      setPlans((p) => [newPlan, ...p]);
      setSelected(newPlan);
      toast('Plan generated successfully', 'success');
    } catch {
      toast('Failed to generate plan', 'error');
    } finally {
      setGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) return <SkeletonCard rows={6} />;

  return (
    <div className="page-enter">
      <div className="flex items-center justify-between mb-6 flex-wrap gap-4 no-print">
        <h1 className="text-3xl font-bold">{t('admin.plan')}</h1>
        {selected && (
          <button id="btn-print-plan" className="btn btn-secondary" onClick={handlePrint}>
            🖨️ {t('admin.printPlan')}
          </button>
        )}
      </div>

      {/* Generate form */}
      <div className="card mb-6 no-print">
        <h2 className="text-lg font-semibold mb-4">⚙️ {t('admin.generatePlan')}</h2>
        <form onSubmit={handleGenerate} className="flex gap-4 flex-wrap items-end">
          {user?.role === 'admin' && (
            <div className="form-group" style={{ minWidth: 180 }}>
              <label className="label">District</label>
              <select id="sel-plan-district" className="input select" value={form.district} onChange={(e) => setForm((f) => ({ ...f, district: e.target.value }))}>
                {DISTRICTS.map((d) => <option key={d}>{d}</option>)}
              </select>
            </div>
          )}
          <div className="form-group" style={{ minWidth: 160 }}>
            <label className="label">{t('admin.targetBeneficiaries')}</label>
            <input id="inp-plan-target" className="input" type="number" min={10} max={10000} value={form.targetBeneficiaries} onChange={(e) => setForm((f) => ({ ...f, targetBeneficiaries: Number(e.target.value) }))} />
          </div>
          <div className="form-group" style={{ minWidth: 180 }}>
            <label className="label">{t('admin.budget')} (₹)</label>
            <input id="inp-plan-budget" className="input" type="number" min={100000} step={100000} value={form.budgetInr} onChange={(e) => setForm((f) => ({ ...f, budgetInr: Number(e.target.value) }))} />
          </div>
          <button id="btn-generate-plan" type="submit" className="btn btn-primary" disabled={generating} style={{ alignSelf: 'flex-end', minHeight: 44 }}>
            {generating ? '⏳ Generating...' : '🗺️ Generate'}
          </button>
        </form>
      </div>

      {/* Plan list */}
      {plans.length > 1 && (
        <div className="flex gap-2 flex-wrap mb-4 no-print">
          {plans.map((p, i) => (
            <button
              key={p._id}
              className={`btn btn-sm ${selected?._id === p._id ? 'btn-primary' : 'btn-secondary'}`}
              onClick={() => setSelected(p)}
              id={`btn-plan-${p._id}`}
            >
              {p.district} Plan {i + 1}
            </button>
          ))}
        </div>
      )}

      {/* Plan document */}
      {selected ? (
        <PlanDocument plan={selected} />
      ) : (
        <EmptyState
          icon="🗺️"
          title="No plans generated"
          description="Use the form above to generate a district livelihood action plan."
        />
      )}
    </div>
  );
}
