/* admin/PerspectivePlan.jsx: Generate and print district livelihood action plan
   SIH26097 PM-AJAY Livelihood Assistant */
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../../AuthContext.jsx';
import { SkeletonCard, EmptyState } from '../../components.jsx';
import { postGeneratePlan, getPlans } from '../../api.js';
import { useToast } from '../../ToastContext.jsx';
import './PerspectivePlan.css';

const DISTRICTS = ['Warangal', 'Adilabad', 'Nalgonda'];

function formatLabel(str) {
  if (!str) return '';
  return str
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function PlanDocument({ plan }) {
  const date = plan.createdAt
    ? new Date(plan.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    : new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

  return (
    <div className="plan-doc" id="plan-print-area">
      {/* Header */}
      <div className="plan-header">
        <div className="plan-logo">🌱</div>
        <div className="plan-header-content">
          <h1 className="plan-title">District Livelihood Action Plan</h1>
          <p className="plan-subtitle">PM-AJAY | GIA Component | SIH26097</p>
          <p className="plan-meta">{plan.district} · Generated {date}</p>
        </div>
      </div>

      {/* Key Summary Metrics */}
      <div className="plan-kpis">
        <div className="plan-kpi">
          <div className="plan-kpi-val">{plan.targetBeneficiaries?.toLocaleString()}</div>
          <div className="plan-kpi-lbl">Target Beneficiaries</div>
        </div>
        <div className="plan-kpi">
          <div className="plan-kpi-val">₹{(plan.budgetInr / 100000).toFixed(1)}L</div>
          <div className="plan-kpi-lbl">Total Budget</div>
        </div>
        <div className="plan-kpi">
          <div className="plan-kpi-val">{plan.projectedImpact?.overallPlacementRatePct}%</div>
          <div className="plan-kpi-lbl">Placement Target</div>
        </div>
        <div className="plan-kpi">
          <div className="plan-kpi-val">₹{plan.projectedImpact?.avgMonthlyIncomeInr?.toLocaleString()}</div>
          <div className="plan-kpi-lbl">Avg Monthly Income</div>
        </div>
      </div>

      {/* Employment Pathway Split */}
      <div className="plan-section">
        <h2>Employment Pathway Split</h2>
        <div className="plan-split">
          <div className="plan-split-item" style={{ background: '#fff7ed', borderColor: '#fed7aa' }}>
            <span style={{ fontSize: '2rem' }}>🏪</span>
            <strong>{plan.projectedImpact?.selfEmploymentCount}</strong>
            <span>Self Employment</span>
          </div>
          <div className="plan-split-item" style={{ background: '#eff6ff', borderColor: '#bfdbfe' }}>
            <span style={{ fontSize: '2rem' }}>💼</span>
            <strong>{plan.projectedImpact?.wageEmploymentCount}</strong>
            <span>Wage Employment</span>
          </div>
        </div>
      </div>

      {/* Sectoral Allocation Table */}
      <div className="plan-section">
        <h2>Sectoral Allocation Plan</h2>
        <div className="plan-table-wrapper">
          <table className="plan-table">
            <thead>
              <tr>
                <th>Sector / Occupation</th>
                <th>Beneficiaries</th>
                <th>Budget Allocated</th>
                <th>Expected Placements</th>
                <th>Training Partners</th>
              </tr>
            </thead>
            <tbody>
              {(plan.allocations || []).map((a, i) => (
                <tr key={i}>
                  <td>
                    <strong>{a.sector}</strong>
                    <br />
                    <span style={{ fontSize: '11px', color: 'var(--text-subtle)' }}>
                      {formatLabel(a.occupationKey)}
                    </span>
                  </td>
                  <td>{a.beneficiaryCount?.toLocaleString()}</td>
                  <td>₹{(a.allocatedBudgetInr / 100000).toFixed(2)}L</td>
                  <td>{a.expectedPlacements?.toLocaleString()}</td>
                  <td style={{ fontSize: '12px', wordBreak: 'break-word', maxWidth: '240px' }}>
                    {(a.trainingPartners || []).join(', ')}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="plan-footer">
        <p>This plan is indicative. Actual targets are subject to district capacity assessment and state approval.</p>
        <p>Generated by SIH26097 AI Livelihood Mapping System | PM-AJAY GIA</p>
      </div>
    </div>
  );
}

export default function PerspectivePlan() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const toast = useToast();

  const [plans, setPlans] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [selected, setSelected] = useState(null);
  const [form, setForm] = useState({
    district: user?.district || 'Warangal',
    targetBeneficiaries: 500,
    budgetInr: 5000000,
  });

  useEffect(() => {
    getPlans()
      .then((res) => {
        const p = res.data.plans || [];
        setPlans(p);
        if (p.length > 0) setSelected(p[0]);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    setGenerating(true);
    try {
      const res = await postGeneratePlan(form);
      const newPlan = res.data.plan;
      setPlans((p) => [newPlan, ...p]);
      setSelected(newPlan);
      toast('Plan generated successfully', 'success');
    } catch {
      toast('Failed to generate plan', 'error');
    } finally {
      setGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="plan-page page-enter">
        <div className="plan-page-header no-print">
          <h1 className="plan-page-title">{t('admin.plan')}</h1>
        </div>
        <SkeletonCard rows={6} />
      </div>
    );
  }

  return (
    <div className="plan-page page-enter">
      {/* Header bar */}
      <div className="plan-page-header no-print">
        <h1 className="plan-page-title">{t('admin.plan')}</h1>
        {selected && (
          <button id="btn-print-plan" className="btn btn-secondary" onClick={handlePrint}>
            🖨️ {t('admin.printPlan')}
          </button>
        )}
      </div>

      {/* Generation Form */}
      <div className="plan-form-card no-print">
        <h2 style={{ fontSize: '16px', fontWeight: 700, marginBottom: '14px', color: 'var(--text-main)' }}>
          ⚙️ {t('admin.generatePlan')}
        </h2>
        <form onSubmit={handleGenerate} className="plan-form-grid">
          {user?.role === 'admin' && (
            <div className="plan-form-field">
              <label className="form-label">District</label>
              <select
                id="sel-plan-district"
                className="input select"
                value={form.district}
                onChange={(e) => setForm((f) => ({ ...f, district: e.target.value }))}
              >
                {DISTRICTS.map((d) => (
                  <option key={d}>{d}</option>
                ))}
              </select>
            </div>
          )}
          <div className="plan-form-field">
            <label className="form-label">{t('admin.targetBeneficiaries')}</label>
            <input
              id="inp-plan-target"
              className="input"
              type="number"
              min={10}
              max={10000}
              value={form.targetBeneficiaries}
              onChange={(e) => setForm((f) => ({ ...f, targetBeneficiaries: Number(e.target.value) }))}
            />
          </div>
          <div className="plan-form-field">
            <label className="form-label">{t('admin.budget')} (₹)</label>
            <input
              id="inp-plan-budget"
              className="input"
              type="number"
              min={100000}
              step={100000}
              value={form.budgetInr}
              onChange={(e) => setForm((f) => ({ ...f, budgetInr: Number(e.target.value) }))}
            />
          </div>
          <button
            id="btn-generate-plan"
            type="submit"
            className="btn btn-primary"
            disabled={generating}
            style={{ alignSelf: 'flex-end', minHeight: '42px', padding: '0 20px' }}
          >
            {generating ? '⏳ Generating...' : '🗺️ Generate'}
          </button>
        </form>
      </div>

      {/* Plan list selector */}
      {plans.length > 1 && (
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '16px' }} className="no-print">
          {plans.map((p, i) => (
            <button
              key={p._id}
              className={`btn btn-sm ${selected?._id === p._id ? 'btn-primary' : 'btn-secondary'}`}
              onClick={() => setSelected(p)}
              id={`btn-plan-${p._id}`}
            >
              {p.district} Plan {i + 1}
            </button>
          ))}
        </div>
      )}

      {/* Plan document */}
      {selected ? (
        <PlanDocument plan={selected} />
      ) : (
        <EmptyState
          icon="🗺️"
          title="No plans generated"
          description="Use the form above to generate a district livelihood action plan."
        />
      )}
    </div>
  );
}
